// @generated by spec-codegen — do not edit by hand.
//
// Source: spytial-core 4.3.0, layout-spec language 2026-07-29
//         (templates/vendor/spytial-language.json)
// Regenerate: cargo run --manifest-path spec-codegen/Cargo.toml
//
// These tables are spytial-core's own description of the layout-spec language,
// lowered to Rust. They drive which keys `#[derive(SpytialDecorators)]` accepts
// and which values it rejects at compile time. The hand-written half of the
// macro — the literal-aware token scanner and the codegen — lives in lib.rs.

// The tables mirror the manifest in full, so some columns are carried for
// reference rather than read by the macro today: `yaml`/`yaml_key` record how
// spytial-core spells each name, `required` and `deprecated_for` record language
// facts the macro does not yet act on, and the version constants stamp the
// source. Dropping them would make the table a lossy view of the manifest and
// the next person's diff harder to read.
#![allow(dead_code)]

/// The spytial-core release these tables were generated from.
pub const SPYTIAL_CORE_VERSION: &str = "4.3.0";

/// The date the layout-spec language last changed, per the manifest. If this
/// has not moved since the tables were generated, nothing the macro emits needs
/// revisiting.
pub const LANGUAGE_VERSION: &str = "2026-07-29";

/// What spytial-core itself does with a value outside a field's vocabulary.
///
/// The macro rejects at compile time regardless — the point of these tables is
/// that a typo should fail loudly here rather than silently render nothing —
/// but the level explains *why* in the error message.
pub mod enforcement {
    /// spytial-core refuses to parse the whole spec.
    pub const PARSE_ERROR: &str = "parse-error";
    /// spytial-core drops the leaf and renders with the default.
    pub const VALUE_IGNORED: &str = "value-ignored";
    /// spytial-core passes the value through; it simply matches nothing.
    pub const UNCHECKED: &str = "unchecked";
}

/// One field's declarative rules.
#[derive(Debug)]
pub struct FieldRule {
    /// The key as written in a Rust attribute (snake_case).
    pub key: &'static str,
    /// The key as spytial-core spells it in YAML.
    pub yaml: &'static str,
    /// Closed vocabulary, if the field has one.
    pub values: Option<&'static [&'static str]>,
    /// Exclusive lower bound (`weight`, `width`, …).
    pub exclusive_min: Option<f64>,
    /// Inclusive lower bound.
    pub min: Option<f64>,
    /// Inclusive upper bound.
    pub max: Option<f64>,
    /// Whether spytial-core requires the field.
    pub required: bool,
    /// See [`enforcement`].
    pub enforcement: Option<&'static str>,
    /// The value spytial-core assumes when the field is absent.
    pub default: Option<&'static str>,
}

/// One authoring attribute, e.g. `#[orientation(...)]`.
#[derive(Debug)]
pub struct AttrSpec {
    /// The Rust attribute name.
    pub attr: &'static str,
    /// The YAML key spytial-core reads it as.
    pub yaml_key: &'static str,
    /// Every key the attribute accepts, in manifest order.
    pub keys: &'static [&'static str],
    /// Per-field rules, in the same order as `keys`.
    pub rules: &'static [FieldRule],
    /// Set when spytial-core has deprecated this form, naming its replacement.
    pub deprecated_for: Option<&'static str>,
}

impl AttrSpec {
    /// The rule for `key`, if the attribute accepts it.
    pub fn rule(&self, key: &str) -> Option<&FieldRule> {
        self.rules.iter().find(|r| r.key == key)
    }
}

/// One nested style block, e.g. `line_style(...)`.
#[derive(Debug)]
pub struct BlockSpec {
    /// The block name as written in a Rust attribute.
    pub block: &'static str,
    /// The block name as spytial-core spells it in YAML.
    pub yaml_key: &'static str,
    /// Per-leaf rules.
    pub rules: &'static [FieldRule],
}

impl BlockSpec {
    /// The rule for `key`, if the block accepts it.
    pub fn rule(&self, key: &str) -> Option<&FieldRule> {
        self.rules.iter().find(|r| r.key == key)
    }
}

/// The spec for `attr`, or `None` if it is not an authoring attribute.
pub fn attr_spec(attr: &str) -> Option<&'static AttrSpec> {
    ATTRS.iter().find(|a| a.attr == attr)
}

/// The spec for a nested style block, e.g. `line_style`.
pub fn block_spec(block: &str) -> Option<&'static BlockSpec> {
    BLOCKS.iter().find(|b| b.block == block)
}

/// Every authoring attribute the derive macro accepts.
pub static ATTRS: &[AttrSpec] = &[
    AttrSpec {
        attr: "attribute",
        yaml_key: "attribute",
        keys: &["field", "selector", "filter", "text_style"],
        rules: &[
            FieldRule {
                key: "field",
                yaml: "field",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "filter",
                yaml: "filter",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "flag",
        yaml_key: "flag",
        keys: &["name"],
        rules: &[FieldRule {
            key: "name",
            yaml: "flag",
            values: Some(&["hideDisconnected", "hideDisconnectedBuiltIns"]),
            exclusive_min: None,
            min: None,
            max: None,
            required: true,
            enforcement: Some("unchecked"),
            default: None,
        }],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "orientation",
        yaml_key: "orientation",
        keys: &["selector", "directions", "negated"],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "directions",
                yaml: "directions",
                values: Some(&[
                    "above",
                    "below",
                    "left",
                    "right",
                    "directlyAbove",
                    "directlyBelow",
                    "directlyLeft",
                    "directlyRight",
                ]),
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "negated",
                yaml: "hold",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "align",
        yaml_key: "align",
        keys: &["selector", "direction", "negated"],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "direction",
                yaml: "direction",
                values: Some(&["horizontal", "vertical"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "negated",
                yaml: "hold",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "cyclic",
        yaml_key: "cyclic",
        keys: &["selector", "direction", "negated"],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "direction",
                yaml: "direction",
                values: Some(&["clockwise", "counterclockwise"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("unchecked"),
                default: Some("clockwise"),
            },
            FieldRule {
                key: "negated",
                yaml: "hold",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "group",
        yaml_key: "group",
        keys: &[
            "selector",
            "name",
            "add_edge",
            "text_style",
            "negated",
            "field",
            "group_on",
            "add_to_group",
        ],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "name",
                yaml: "name",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "add_edge",
                yaml: "addEdge",
                values: Some(&["none", "togroup", "fromgroup"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: Some("none"),
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "negated",
                yaml: "hold",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "field",
                yaml: "field",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "group_on",
                yaml: "groupOn",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "add_to_group",
                yaml: "addToGroup",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "atom_color",
        yaml_key: "atomColor",
        keys: &["value", "selector"],
        rules: &[
            FieldRule {
                key: "value",
                yaml: "value",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
        ],
        deprecated_for: Some("atomStyle"),
    },
    AttrSpec {
        attr: "atom_style",
        yaml_key: "atomStyle",
        keys: &[
            "selector",
            "fill_style",
            "border_style",
            "icon_style",
            "text_style",
            "show_label",
        ],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "fill_style",
                yaml: "fillStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "border_style",
                yaml: "borderStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "icon_style",
                yaml: "iconStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "show_label",
                yaml: "showLabel",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: Some("true"),
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "size",
        yaml_key: "size",
        keys: &["width", "height", "selector"],
        rules: &[
            FieldRule {
                key: "width",
                yaml: "width",
                values: None,
                exclusive_min: Some(0.0),
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "height",
                yaml: "height",
                values: None,
                exclusive_min: Some(0.0),
                min: None,
                max: None,
                required: true,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "icon",
        yaml_key: "icon",
        keys: &["selector", "path", "show_labels"],
        rules: &[
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "path",
                yaml: "path",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "show_labels",
                yaml: "showLabels",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: Some("false"),
            },
        ],
        deprecated_for: Some("atomStyle"),
    },
    AttrSpec {
        attr: "edge_style",
        yaml_key: "edgeStyle",
        keys: &[
            "field",
            "selector",
            "filter",
            "line_style",
            "text_style",
            "show_label",
            "hidden",
            "value",
            "style",
            "weight",
        ],
        rules: &[
            FieldRule {
                key: "field",
                yaml: "field",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "filter",
                yaml: "filter",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "line_style",
                yaml: "lineStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "show_label",
                yaml: "showLabel",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: Some("true"),
            },
            FieldRule {
                key: "hidden",
                yaml: "hidden",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: Some("false"),
            },
            FieldRule {
                key: "value",
                yaml: "value",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "style",
                yaml: "style",
                values: Some(&["solid", "dashed", "dotted"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: None,
            },
            FieldRule {
                key: "weight",
                yaml: "weight",
                values: None,
                exclusive_min: Some(0.0),
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "hide_field",
        yaml_key: "hideField",
        keys: &["field", "selector", "filter"],
        rules: &[
            FieldRule {
                key: "field",
                yaml: "field",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "filter",
                yaml: "filter",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "hide_atom",
        yaml_key: "hideAtom",
        keys: &["selector"],
        rules: &[FieldRule {
            key: "selector",
            yaml: "selector",
            values: None,
            exclusive_min: None,
            min: None,
            max: None,
            required: true,
            enforcement: Some("unchecked"),
            default: None,
        }],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "inferred_edge",
        yaml_key: "inferredEdge",
        keys: &["name", "selector", "draw", "line_style", "text_style"],
        rules: &[
            FieldRule {
                key: "name",
                yaml: "name",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "selector",
                yaml: "selector",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "draw",
                yaml: "draw",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("parse-error"),
                default: None,
            },
            FieldRule {
                key: "line_style",
                yaml: "lineStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
    AttrSpec {
        attr: "tag",
        yaml_key: "tag",
        keys: &["to_tag", "name", "value", "text_style"],
        rules: &[
            FieldRule {
                key: "to_tag",
                yaml: "toTag",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "name",
                yaml: "name",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "value",
                yaml: "value",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: true,
                enforcement: Some("unchecked"),
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
        deprecated_for: None,
    },
];

/// Every nested style block the derive macro accepts.
pub static BLOCKS: &[BlockSpec] = &[
    BlockSpec {
        block: "line_style",
        yaml_key: "lineStyle",
        rules: &[
            FieldRule {
                key: "color",
                yaml: "color",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "pattern",
                yaml: "pattern",
                values: Some(&["solid", "dashed", "dotted"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: None,
            },
            FieldRule {
                key: "weight",
                yaml: "weight",
                values: None,
                exclusive_min: Some(0.0),
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: None,
            },
            FieldRule {
                key: "highlight",
                yaml: "highlight",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
    },
    BlockSpec {
        block: "text_style",
        yaml_key: "textStyle",
        rules: &[
            FieldRule {
                key: "size",
                yaml: "size",
                values: Some(&["small", "normal", "large"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: Some("normal"),
            },
            FieldRule {
                key: "color",
                yaml: "color",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
    },
    BlockSpec {
        block: "border_style",
        yaml_key: "borderStyle",
        rules: &[
            FieldRule {
                key: "color",
                yaml: "color",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "width",
                yaml: "width",
                values: None,
                exclusive_min: Some(0.0),
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: None,
            },
        ],
    },
    BlockSpec {
        block: "fill_style",
        yaml_key: "fillStyle",
        rules: &[FieldRule {
            key: "color",
            yaml: "color",
            values: None,
            exclusive_min: None,
            min: None,
            max: None,
            required: false,
            enforcement: None,
            default: None,
        }],
    },
    BlockSpec {
        block: "icon_style",
        yaml_key: "iconStyle",
        rules: &[
            FieldRule {
                key: "path",
                yaml: "path",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "placement",
                yaml: "placement",
                values: Some(&["full", "badge"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: Some("value-ignored"),
                default: Some("full"),
            },
            FieldRule {
                key: "opacity",
                yaml: "opacity",
                values: None,
                exclusive_min: None,
                min: Some(0.0),
                max: Some(1.0),
                required: false,
                enforcement: Some("value-ignored"),
                default: Some("1"),
            },
        ],
    },
    BlockSpec {
        block: "add_edge",
        yaml_key: "addEdge",
        rules: &[
            FieldRule {
                key: "points",
                yaml: "points",
                values: Some(&["none", "togroup", "fromgroup"]),
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: Some("none"),
            },
            FieldRule {
                key: "line_style",
                yaml: "lineStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
            FieldRule {
                key: "text_style",
                yaml: "textStyle",
                values: None,
                exclusive_min: None,
                min: None,
                max: None,
                required: false,
                enforcement: None,
                default: None,
            },
        ],
    },
];

/// Direction pairs `orientation` rejects together (`above` with `below`,
/// `left` with `right`). spytial-core enforces these at parse time.
pub static ORIENTATION_AT_MOST_ONE_OF: &[&[&str]] = &[&["above", "below"], &["left", "right"]];

/// A `directly*` direction narrows the rest of the list to these values.
pub static ORIENTATION_NARROWS_TO: &[(&str, &[&str])] = &[
    ("directlyAbove", &["above", "directlyAbove"] as &[&str]),
    ("directlyBelow", &["below", "directlyBelow"] as &[&str]),
    ("directlyLeft", &["left", "directlyLeft"] as &[&str]),
    ("directlyRight", &["right", "directlyRight"] as &[&str]),
];
